### ISSUE TITLE
Bot only responds to owner (who added the bot), crashes when someone else uses it.

### ISSUE THREAD

**Issue by DudeShift** [nizewn/Dodong#42]
Recently updated my Dodong bot (new docker image and new discord bot), added to my server, and works great for me.

However, the bot does not respond to any other user on the server (ie, no response from -help), and crashes.

The docker container logs are: 
```
/bot/node_modules/discord.js/src/util/BitField.js:168
    throw new DiscordjsRangeError(ErrorCodes.BitFieldInvalid, bit);
    ^

RangeError [BitFieldInvalid]: Invalid bitfield flag or number: SEND_MESSAGES.
    at Function.resolve (/bot/node_modules/discord.js/src/util/BitField.js:168:11)
    at PermissionsBitField.has (/bot/node_modules/discord.js/src/util/BitField.js:60:28)
    at PermissionsBitField.has (/bot/node_modules/discord.js/src/util/PermissionsBitField.js:92:82)
    at /bot/events/messageCreate.js:17:52
    at Bot.emit (node:events:513:28)
    at MessageCreateAction.handle (/bot/node_modules/discord.js/src/client/actions/MessageCreate.js:28:14)
    at Object.module.exports [as MESSAGE_CREATE] (/bot/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/bot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:352:31)
    at WebSocketShard.onPacket (/bot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:480:22)
    at WebSocketShard.onMessage (/bot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:320:10) {
  code: 'BitFieldInvalid'
}
```
When making the bot I have allowed for Server Members Intent and Message Content Intent.
For the scope and bot permissions, I tried looking in client.js and [set the following image (couldn't find view channel in list though)](https://i.imgur.com/gi25Eoy.png)

This issue looks similar to Issue #37 due to the SEND_MESSAGES but I have looked at the client.js and the required permissions are in CamelCase (ie, "SendMessages").

**Comment by nizewn** [comment]
Looks like I forgot to update the permissions for each command. Thanks!
